/*
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl2.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsl2.ui.internal.Mydsl2Activator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Mydsl2Activator.getInstance().getInjector("org.xtext.example.mydsl2.MyDsl");
	}

}
