/**
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl2.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Def Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.DefRef#getDef <em>Def</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getDefRef()
 * @model
 * @generated
 */
public interface DefRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Def</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def</em>' reference.
   * @see #setDef(Def)
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getDefRef_Def()
   * @model
   * @generated
   */
  Def getDef();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.myDsl.DefRef#getDef <em>Def</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Def</em>' reference.
   * @see #getDef()
   * @generated
   */
  void setDef(Def value);

} // DefRef
