/**
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl2.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.Model#getDefs <em>Defs</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.Model#getUses <em>Uses</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Defs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl2.myDsl.Def}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Defs</em>' containment reference list.
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getModel_Defs()
   * @model containment="true"
   * @generated
   */
  EList<Def> getDefs();

  /**
   * Returns the value of the '<em><b>Uses</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl2.myDsl.Use}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uses</em>' containment reference list.
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getModel_Uses()
   * @model containment="true"
   * @generated
   */
  EList<Use> getUses();

} // Model
