/**
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl2.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.myDsl.Use#getDefRefs <em>Def Refs</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getUse()
 * @model
 * @generated
 */
public interface Use extends EObject
{
  /**
   * Returns the value of the '<em><b>Def Refs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl2.myDsl.DefRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def Refs</em>' containment reference list.
   * @see org.xtext.example.mydsl2.myDsl.MyDslPackage#getUse_DefRefs()
   * @model containment="true"
   * @generated
   */
  EList<DefRef> getDefRefs();

} // Use
