/*
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl2.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.mydsl2.ui.internal.Mydsl2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Mydsl2Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Mydsl2Activator activator = Mydsl2Activator.getInstance();
		return activator != null ? activator.getInjector(Mydsl2Activator.ORG_XTEXT_EXAMPLE_MYDSL2_MYDSL) : null;
	}

}
