/*
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl2;

import org.eclipse.xtext.parser.IParser;
import org.xtext.example.mydsl2.parser.antlr.CustomMyDslParser;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
	
	@Override
    public Class<? extends IParser> bindIParser() {
        return CustomMyDslParser.class;
    }
}
