/*
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.partialEditing.IPartialEditingContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.IProposalConflictHelper;
import org.xtext.example.mydsl2.ui.ide.contentassist.antlr.CustomAntlrConflictProposalHelper;
import org.xtext.example.mydsl2.ui.ide.contentassist.antlr.CustomMyDslParser;
import org.xtext.example.mydsl2.ui.ide.contentassist.antlr.CustomPartialMyDslContentAssistParser;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyDslUiModule extends AbstractMyDslUiModule {

	public MyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IPartialEditingContentAssistParser> bindIPartialEditingContentAssistParser() {
		return CustomPartialMyDslContentAssistParser.class;
	}
	
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return CustomMyDslParser.class;
	}
	
	@Override
	public Class<? extends IProposalConflictHelper> bindIProposalConflictHelper() {
		return CustomAntlrConflictProposalHelper.class;
	}
}
